### ISSUE TITLE
changing Icon

### ISSUE THREAD

**Issue by kouroshst** [fullhdpixel/react-leaflet-locate-control#1]
Hi, I use font-awesome differently in my project

         <FontAwesomeIcon icon={faBook}/>

is there a way to use this syntax in your library?
for example change the span holder of icon to the syntax given?

**Comment by thijssmudde** [comment]
Not atm. Its a good feature request. You can fork the project and add this yourself. I will merge it here.

**Comment by thijssmudde** [comment]
See my commentary here: https://github.com/fullhdpixel/react-leaflet-locate-control/pull/3
